global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9096

rule_files:

	# Наш файл с правилами уведомлений 
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ficus_exporter"
    static_configs:
      - targets: ["85.193.85.180:9100:9100"]
