route:
  receiver: 'telegram'
  routes:    
  - receiver: 'telegram'
    group_wait: 10s
    matchers:
    - severity=~"warning|critical"

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: ""
    chat_id: -12345
